try {
    hello();
} catch (error) {
    console.log(error);
}

try {
    anotherFunction();
} catch {
    console.log('this is a error');
}